version: "3.8"

services:
  postgres:
    container_name: postgres_db
    image: postgres:15
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitoring
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER} || exit 1"]
      interval: 10s
      retries: 5
      timeout: 5s

  postgres_exporter:
    container_name: postgres_exporter
    image: prometheuscommunity/postgres-exporter
    restart: always
    env_file: .env
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable" 
    depends_on:
      - postgres
    networks:
      - monitoring

  redis:
    container_name: redis_cache
    image: redis:7
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file: .env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      retries: 5
      timeout: 5s

  redis_exporter:
    container_name: redis_exporter
    image: oliver006/redis_exporter
    restart: always
    env_file: .env
    ports:
      - "9121:9121"
    command: ["--redis.addr=redis://redis:6379", "--redis.password=${REDIS_PASSWORD}"]
    depends_on:
      - redis
    networks:
      - monitoring

  prometheus:
    container_name: prometheus_monitoring
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090/-/healthy"]
      interval: 10s
      retries: 5
      timeout: 5s

  grafana:
    container_name: grafana_dashboard
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - monitoring

networks:
  monitoring:

volumes:
  postgres_data:
  redis_data:
  grafana_data: