{
 "title": "PostgreSQL",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "PostgreSQL Instance Health & Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "PostgreSQL Instance Up",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Deadlocks per Minute",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_deadlocks{datname=~\"$datname\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(pg_stat_activity_count{})) / \n(sum(pg_settings_max_connections{})) * 100",
     "legendFormat": "{{Active Connections}}"
    }
   ]
  },
  {
   "title": "Transactions & Performance Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Transaction  Rate",
   "type": "stat",
   "description": "Transactions committed + roolback per minute\n\nSource: pg_stat_database,xact_commit + xact_rollback",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((rate(pg_stat_database_xact_commit{}[1m])))+sum((rate(pg_stat_database_xact_rollback{}[1m])))",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(pg_stat_database_blks_hit{}) by (datname) * 100) / \n(sum(pg_stat_database_blks_hit{}) by (datname) + \nsum(pg_stat_database_blks_read{}) by (datname))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory & Buffer Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Shared Buffer Hits",
   "type": "gauge",
   "description": "Shared buffer hits vs reads from disc",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_blks_hit{})/(sum(pg_stat_database_blks_hit{})+sum(pg_stat_database_blks_read{}))*100"
    }
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{}"
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_settings_work_mem_bytes{}" }
   ]
  },
  { "title": "Connection & Worker Limits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Max Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "pg_settings_max_connections{}" }
   ]
  },
  {
   "title": "Max Worker Processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_worker_processes{}"
    }
   ]
  }
 ]
}