{
 "title": "Redis",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Keys",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(redis_db_keys{})" }
     ]
    },
    {
     "title": "Clients",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(redis_connected_clients{})" }
     ]
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Commands per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "avg(irate(redis_commands_total{} [1m])) by (cmd)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Command Latency per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(irate(redis_commands_duration_seconds_total{}[1m])) by (cmd)\n  /\navg(irate(redis_commands_total{}[1m])) by (cmd)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache & Data Management",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hit & Miss Ratio ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(\n  irate(redis_keyspace_hits_total[1m]) / \n  (irate(redis_keyspace_hits_total[1m]) + irate(redis_keyspace_misses_total[1m])) \n) \n* 100 \n",
       "legendFormat": "Hit Ratio (%)"
      },
      {
       "expr": "(\n  irate(redis_keyspace_misses_total[1m]) / \n  (irate(redis_keyspace_hits_total[1m]) + irate(redis_keyspace_misses_total[1m])) \n) * 100 ",
       "legendFormat": "Miss Ratio (%)"
      }
     ]
    },
    {
     "title": "Keys Eviction & Expiration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(redis_expired_keys_total{}[1m])",
       "legendFormat": "Expired"
      },
      {
       "expr": "irate(redis_evicted_keys_total{}[1m])",
       "legendFormat": "Evicted"
      }
     ]
    }
   ]
  }
 ]
}